pipeline {
    agent any

    stages {

        stage('Quality Control') {
            steps {
                echo 'Running Quality Control'
                sh 'mkdir -p results'
                sh 'echo QC completed > results/qc_report.txt'
            }
        }

        stage('Alignment') {
            steps {
                echo 'Running Alignment'
                sh 'echo Alignment completed > results/alignment.bam'
            }
        }

        stage('Variant Calling') {
            steps {
                echo 'Running Variant Calling'
                sh 'echo Variant calling completed > results/variants.vcf'
            }
        }

    }
}